#!/bin/bash
#---------------------------------------------------------
# run_simulation
# Author: Amy Ousterhout
#---------------------------------------------------------

#---------------------------------------------------------
# This script compiles and runs the momose simulation
# and does necessary post-processing for c++ simulator.
#
# The default is to not compile anything - by specifying expat and momose as args, you
# con instruct it to compile the expat libs and momose.
#
# commands for java simulator
# javac -classpath ./src:./lib/gluegen-rt.jar:./lib/jogl.jar -d ./bin ./src/gui/Momose.java
# java -cp ./bin:./lib/gluegen-rt.jar:./lib/jogl.jar -Djava.library.path=./lib gui.Momose -d32
#
#---------------------------------------------------------
C2="c2"
COUNT=0

# add libraries to be preloaded if running on c2
if [ "$1" = $C2 ]; then
    export LD_PRELOAD="./../extlibs/expat/lib/libexpat.so.1"
    echo $LD_PRELOAD
fi

# remove existing data files
for f in $( ls ./plotting/data_* ); do
    echo "Removing data file: " $f
    rm -f $f
done

# removing temp files in configs directory
echo "Removing temp files in configs directory"
cd ./momosecpp/configs
rm -f *~
cd ../..


# run momose and process the output into ./plotting/data_??.csv
# where ?? is a number
echo "Running the simulation"
cd ./momosecpp/src
for f in $( ls ../configs/RWM_config_* ); do
    echo "Running sim for file: " $f
    ./momose -f $f
    echo "Processing data for file: " $f
    cd ../../plotting
    python process_provision.py "../momosecpp/output/messageRecorderOutput.csv" 6 > ./data_$COUNT.csv
    cd ../momosecpp/src
    cp ../output/messageRecorderOutput.csv ../output/messageRecorderOutput_$COUNT.csv
    let COUNT=COUNT+1
done

cd ../..